import type { UiHeaderRuntime } from "@termco/ui-header-base";

const noop = () => {};

/** Complete public runtime fixture used by the source-owned header tests. */
export function createHeaderRuntime(
  overrides: Partial<UiHeaderRuntime> = {},
): UiHeaderRuntime {
  return {
    platform: "linux",
    customWindowControls: true,
    zenMode: false,
    aiPanelOpen: false,
    agentsViewOpen: false,
    settingsViewOpen: false,
    editorDirty: false,
    activeTabId: 1,
    activeRigId: "rig-a",
    tabs: [],
    allTabs: [],
    rigs: [],
    agentSessions: [],
    agentNotifications: [],
    findTarget: null,
    palette: {
      open: false,
      show: noop,
      close: noop,
      setAnchor: noop,
      setInputSlot: noop,
    },
    selectTab: noop,
    splitTab: noop,
    newTab: noop,
    newBlockTab: noop,
    newPrivateTab: noop,
    newPreviewTab: noop,
    newEditor: noop,
    newGitGraph: noop,
    closeTab: noop,
    closeMany: noop,
    newTabRightOf: noop,
    duplicateTab: noop,
    pinTab: noop,
    renameTab: noop,
    reorderTab: noop,
    overrideLanguage: noop,
    toggleSidebar: noop,
    saveActiveFile: noop,
    toggleAiPanel: noop,
    toggleAgentsView: noop,
    toggleSettings: noop,
    activateAgent: noop,
    activateLocalAgent: noop,
    markAgentNotificationsRead: noop,
    clearAgentNotifications: noop,
    activateRig: noop,
    renameRig: noop,
    deleteRig: noop,
    reorderRigs: noop,
    newRig: noop,
    newSshRig: noop,
    newTabInRig: noop,
    jumpToTab: noop,
    moveTabToRig: noop,
    reorderRigTab: noop,
    minimizeWindow: noop,
    toggleMaximizeWindow: noop,
    closeWindow: noop,
    isWindowMaximized: async () => false,
    ...overrides,
  };
}
